### ISSUE TITLE
Kiron (reseach)

### ISSUE THREAD

**Issue by Danaal** [Danaal/Open_Science_Project#10]

**Comment by AbbasKalantari** [comment]
**_Free education for those who cannot pay for it._**
Kiron is an NGO working to prepare free education for people who are not able to pay for their education. It even helps them to verify their learning and work closely with some universities to help Kiron students get into university.

Advantages: The platform is fully online which enables the organization to make their service reusable and reproducible. It provides evaluation which is a good thing in the learning process. It also directly helps people to have this chance to grow despite their Economic situation.

Issues:
it does not have any innovation in it and because traditional evaluation processes have some flaws it is possible that companies and other employers would not trust in their certificates.
Accessibility for people who cannot pay for their education means that they cannot pay for some high-tech tools like broadbands, laptops, smartphones, etc. There are some people who have access to these things but I assume the main people who are in severe condition do not have access to any online platforms.
 It is not widely discoverable for the people in bad conditions and not being aware of these NGOs may never give them this chance to try it. Besides, the communication among those people are poor and somehow engineered (refugees and etc.) Therefore, there is a high need for a well developed communication channel for this purpose.
